# Generated by Django 4.2.4 on 2023-08-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type_name',
            field=models.CharField(choices=[('Text', 'Text'), ('Multiple Choice', 'Multiple Choice'), ('Single Choice', 'Single Choice'), ('Scale', 'Scale'), ('Date', 'Date'), ('File Upload', 'File Upload'), ('Consent', 'Consent'), ('Dropdown', 'Dropdown'), ('Matrix', 'Matrix')], max_length=50),
        ),
    ]
