# Generated by Django 4.2.4 on 2023-08-17 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointmentconsent_appointmentinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentconsent',
            name='acknowledgement1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentconsent',
            name='acknowledgement2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentconsent',
            name='acknowledgement3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentconsent',
            name='acknowledgement4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='appointmentFor',
            field=models.CharField(default='Myself', max_length=100),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='emergencyContactFirstName',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='emergencyContactLastName',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='emergencyContactPhoneNumber',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='prefferedAppointmentDateAndTime',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='prefferedProvidedGender',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='prefferedVisitType',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='pronouns',
            field=models.CharField(default='He/Him', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='reasonForVisit',
            field=models.CharField(default='default', max_length=1000),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='relationshipWithEmergencyContact',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='servicesInterestedIn',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AddField(
            model_name='appointmentinsuranceinfo',
            name='insuranceCompany',
            field=models.CharField(default='default', max_length=400),
        ),
        migrations.AddField(
            model_name='appointmentinsuranceinfo',
            name='isSelfPayPayment',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='appointmentinsuranceinfo',
            name='isUsingInsurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentinsuranceinfo',
            name='subscriberMemberId',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
