# Generated by Django 4.2.4 on 2023-08-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointmentconsent_acknowledgement1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentinsuranceinfo',
            name='backImage',
            field=models.FileField(blank=True, null=True, upload_to='insurance_docs/'),
        ),
        migrations.AddField(
            model_name='appointmentinsuranceinfo',
            name='frontImage',
            field=models.FileField(blank=True, null=True, upload_to='insurance_docs/'),
        ),
    ]
